<?php
// Random PHP code generated by LLaMA
$number = 42;
$string = "Hello, World!";
$boolean = true;
$array = array(1, 2, 3);
$object = new stdClass();
echo $number . "\n";
echo $string . "\n";
echo $boolean . "\n";
echo $array[0] . "\n";
?>